"""Markdown documentation generation for SDK asset packages."""

from __future__ import annotations

from typing import Any

from vendor_sdk.vendor_models import AssetBlueprint, AssetGenerationResult


def format_package_readme(result: AssetGenerationResult) -> str:
    """Render README.md for a generated asset package."""
    blueprint = result.blueprint
    lines = [
        f"# {blueprint.title}",
        "",
        "Generated by VoicePilot Vendor Asset SDK.",
        "",
        "## Vendor",
        "",
        f"- **Vendor:** {blueprint.vendor.name}",
        f"- **Product:** {blueprint.product.name}",
        f"- **Category:** {blueprint.product.default_category}",
        "",
        "## Assets",
        "",
        "| Type | Asset ID | Quality |",
        "| --- | --- | --- |",
    ]

    for asset in result.assets:
        asset_id = str(asset["asset_id"])
        score = result.quality_scores.get(asset_id, 0)
        lines.append(f"| {asset['asset_type']} | {asset_id} | {score}/100 |")

    lines.extend(
        [
            "",
            "## Relationships",
            "",
            "Related assets in this package:",
            "",
        ]
    )
    for asset_id in blueprint.related_asset_ids:
        lines.append(f"- {asset_id}")

    lines.extend(
        [
            "",
            "## Validation",
            "",
            f"- Factory validation: {'PASS' if result.validation_passed else 'FAIL'}",
            f"- Minimum quality target: 95/100",
            "",
            "## Editing Guidance",
            "",
            "These files are deterministic scaffolds. Engineers should review and edit:",
            "",
            "- Symptoms and expected findings",
            "- Resolution and rollback steps",
            "- Verification commands",
            "- Vendor references",
            "",
            "Re-run `voicepilot assets validate` after editing before publishing.",
            "",
        ]
    )
    return "\n".join(lines)


def format_asset_markdown(asset: dict[str, Any]) -> str:
    """Render human-readable markdown for one asset."""
    lines = [
        f"# {asset['title']}",
        "",
        f"- **Asset ID:** {asset['asset_id']}",
        f"- **Type:** {asset['asset_type']}",
        f"- **Vendor:** {asset['vendor']}",
        f"- **Product:** {asset['product']}",
        f"- **Severity:** {asset.get('severity', 'medium')}",
        "",
        "## Summary",
        "",
        str(asset.get("summary", "")),
        "",
    ]

    for section, key in (
        ("Symptoms", "symptoms"),
        ("Expected Findings", "expected_findings"),
        ("Likely Causes", "known_causes"),
        ("Resolution", "known_resolution"),
        ("Recommended Actions", "recommended_actions"),
        ("Rollback", "rollback_steps"),
        ("Verification Steps", "verification_steps"),
        ("References", "references"),
        ("Related Assets", "related_asset_ids"),
    ):
        values = asset.get(key)
        if values:
            lines.extend([f"## {section}", ""])
            if isinstance(values, list):
                lines.extend(f"- {item}" for item in values)
            else:
                lines.append(str(values))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"
